typedef char td_char;
typedef wchar td_wchar;
typedef octet td_octet;
typedef short td_short;
typedef unsigned short td_ushort;
typedef long td_long;
typedef unsigned long td_ulong;
typedef long long td_longlong;
typedef unsigned long long td_ulonglong;
typedef float td_float;
typedef double td_double;
typedef long double td_ldouble;
typedef boolean td_boolean;
typedef string td_string;

struct TypeDef_ValidTypes{
    td_char a;
    td_wchar b;
    td_octet c;
    td_short d;
    td_ushort e;
    td_long f;
    td_ulong g;
    td_longlong h;
    td_ulonglong i;
    td_float j;
    td_double k;
    td_ldouble l;
    td_boolean m;
    td_string n;
}