enum global_enum{
    A,
    B,
    C
};

module nest{
    enum nested_enum{
        A, B, C, D
    };
}


module nest{
    struct nested_enums{
        nest::nested_enum a;
        global_enum b;
    };
}

struct enums{
    nest::nested_enum a;
    global_enum b;
};
