/*
    char
    wchar
    octet
    short
    unsigned short
    long
    unsigned long
    long long
    unsigned long long
    float
    double
    long double
    boolean
    string
    /*

struct Valid_Types{
    char a;
    wchar b;
    octet c;
    short d;
    unsigned short e;
    long f;
    unsigned long g;
    long long h;
    unsigned long long i;
    float j;
    double k;
    long double l;
    boolean m;
    string n;
}


