/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
	struct Message{
		string inst_name;
		long time;
	};

	/// A very simple interface
	interface Hello
	{
		void send(in Test::Message message);
	};
};
