// This method collects a list of Node names from the current Jenkins instance
@NonCPS
def nodeNames() {
  return jenkins.model.Jenkins.instance.nodes.collect { node -> node.name }
}

def getLabels(String name){
    def computer = Jenkins.getInstance().getComputer(name)
    def node = computer.getNode()
    if(computer.isOnline()){
        return node.getLabelString()
    }
    return ""
}

//Check that git url parameter exists in jenkins configuration
def git_url = ""
git_url = env.GIT_URL
if(git_url == null){
    print("ERROR: \"GIT_URL\" string parameter missing in build configuration")
    currentBuild.result = 'FAILURE'
    return
}

//Check that git credential parameter exists in jenkins configuration
def git_credential_id = ""
git_credential_id = env.GIT_CREDENTIAL_ID
if(git_credential_id == null) {
    print("ERROR: \"GIT_CREDENTIAL_ID\" credential parameter missing in build configuration")
    currentBuild.result = 'FAILURE'
    return
}

def names = nodeNames()
//Filter re nodes
def filtered_names = []
for(n in names){
    if(getLabels(n).contains("re")){
        filtered_names << n
        print("Got Node: " + n)
    }
}

def default_git_url = "https://github.com/cdit-ma/re_gen.git"

//Set git url to default if empty
if(!git_url){
    git_url = default_git_url
}

//Checkout re_gen source onto master node and stash
stage('Checkout'){
    node("master"){
        dir("re_gen"){
            deleteDir()
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: false, reference: '', trackingSubmodules: false]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: git_credential_id, url: git_url]]])    
            stash includes: "**", name: "re_gen_source"
        }
    }
}

//Unstash and build on all re nodes
stage('Deploy'){
    def builders = [:]
    for(n in filtered_names){
        def node_name = n
        builders[node_name] = {
            node(node_name){
                dir("${RE_GEN_PATH}"){
                    unstash "re_gen_source"
                }
            }
        }
    }
    parallel builders
}


