/* This Jenkinsfile:
    1. Pulls the latest logan source from a specified git repo (defaults to github.com)
    2. Stashes+pops this repo to all nodes with the "logan" tag
    3. Builds logan for production use on these nodes
*/

//Collect a list of Node names from the current Jenkins instance
@NonCPS
def nodeNames() {
  return jenkins.model.Jenkins.instance.nodes.collect { node -> node.name }
}

//Get labels attached to node name
def getLabels(String name){
    def computer = Jenkins.getInstance().getComputer(name)
    def node = computer.getNode()
    if(computer.isOnline()){
        return node.getLabelString()
    }
    return ""
}

//Check that the correct params are specified in the jenkins configuration
def git_url = ""
git_url = env.GIT_URL
if(git_url == null){
    print("ERROR: \"GIT_URL\" string parameter missing in build configuration")
    currentBuild.result = 'FAILURE'
    return
}

def git_credential_id = ""
git_credential_id = env.GIT_CREDENTIAL_ID
if(git_credential_id == null){
    print("ERROR: \"GIT_CREDENTIAL_ID\" credential parameter missing in build configuration")
    currentBuild.result = 'FAILURE'
    return
}

def names = nodeNames()

//Filter out non logan nodes
def filtered_names = []
for(n in names){
    if(getLabels(n).contains("logan")){
        filtered_names << n
        print("Got Node: " + n)
    }
}

//If param is empty, use default
def default_git_url = "https://github.com/cdit-ma/logan.git"
if(!git_url){
    git_url = default_git_url
}

//Checkout logan on master node and stash
stage('Checkout'){
    node("master"){
        dir("logan"){
            deleteDir()
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: false, reference: '', trackingSubmodules: false]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: git_credential_id, url: git_url]]])    
            stash includes: "**", name: "logan_source"
        }
    }
}

//Unstash on all logan nodes
stage('Checkout'){   
    def builders = [:]
    for(n in filtered_names){
        def node_name = n
        builders[node_name] = {
            node(node_name){
            def loganPath = "${LOGAN_PATH}"
                dir(loganPath){
                    unstash "logan_source"
                }
            }
        }
    }
    parallel builders
}

//Build on all logan nodes
stage('Build'){
    def builders = [:]
    for(n in filtered_names){
        def node_name = n
        builders[node_name] = {
                node(node_name){
                    def loganPath = "${LOGAN_PATH}"
                    withEnv(['CMAKE_MODULE_PATH=' + loganPath + '/cmake_modules']){
                        dir(loganPath + '/build'){
                            sh 'cmake ..'
                            sh 'make -j6'
                        }
                    }
            }
        }
    }
    parallel builders
}
