enum global_enum{
    A,
    B,
    C
};

module nest{
    interface TestInterface{
        void TestMethod(void);
        /*The interface body goes here. */
    };
}

struct enums{
    global_enum b;
};


interface TestInterface{
    void TestMethod(void);
    /*The interface body goes here. */
};