/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
	union UnionEnum switch (long)
	{
		case 1: short enum_short;
		case 2: string enum_string;
		case 3: long enum_long;
		
	};

	struct Message2{
		string inst_name;
		long time;
		//long long_bois[25];
		//UnionEnum test;
		//sequence<long, 50> long_bois; 
	};
	

	struct Message{
		string inst_name;
		long time;
		long long_bois[25];
		UnionEnum test;
		//sequence<long, 50> long_bois; 
	};
	
	/// A very simple interface
	interface Hello
	{
		exception TestException{
			string message;
		};

		void send(in Test::Message2 message);
		void send22(in Test::Message message) raises(TestException);
	};
};
