/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
struct Message2{
	long time2;
	string inst_name2;
};

/// A very simple interface
interface Hello
{
	oneway void send22(in Test::Message2 message);
};
};
