#ifndef ENUMERATIONC_H
#define ENUMERATIONC_H

#include <QStringList>
#include <QString>
//#include <QColor>
#include <QList>
#include <QHash>
#include "version.h"

enum RECT_VERTEX{RV_NONE, RV_LEFT, RV_TOPLEFT, RV_TOP, RV_TOPRIGHT, RV_RIGHT, RV_BOTTOMRIGHT, RV_BOTTOM, RV_BOTTOMLEFT};

//enum NOTIFICATION_TYPE{NT_NONE, NT_INFO, NT_WARNING, NT_ERROR, NT_CRITICAL};

enum ERROR_TYPE{ET_OKAY, ET_WARNING, ET_CRITICAL, ET_INFO};
enum VIEW_STATE{VS_NONE, VS_SELECTED, VS_RUBBERBAND, VS_RUBBERBANDING, VS_CONNECT, VS_MOVING, VS_RESIZING, VS_CONNECTING, VS_PAN, VS_PANNING};

enum VIEW_ASPECT_POS{VAP_NONE, VAP_TOPLEFT, VAP_TOPRIGHT, VAP_BOTTOMRIGHT, VAP_BOTTOMLEFT};

enum VIEW_THEME{VT_NO_THEME, VT_LIGHT_THEME, VT_NORMAL_THEME, VT_DARK_THEME};
enum DOCK_TYPE{UNKNOWN_DOCK, PARTS_DOCK, DEFINITIONC_DOCK, FUNCTIONC_DOCK, HARDWARE_DOCK};

enum NODE_CLASS{NC_NONE, NC_DEPLOYMENT_DEFINITIONS, NC_WORKER_DEFINITIONS};
enum COLOR_SHADE{LIGHTER_SHADE, NORMAL_SHADE, DARKER_SHADE};

#define TOOLBAR_SEPERATOR_WIDTH 8


#define MINIMUM_TEXT_SIZE 6

//#define DIALOG_MARGIN 10
#define DIALOG_MARGIN 5
#define DIALOG_SPACING 5
#define DIALOG_MIN_WIDTH 400
#define DIALOG_MIN_HEIGHT 250

enum class VIEW_ASPECT;
extern QList<VIEW_ASPECT> GET_VIEW_ASPECTS();
extern VIEW_ASPECT_POS GET_ASPECT_POS(VIEW_ASPECT aspect);
extern RECT_VERTEX GET_ASPECT_VERTEX(VIEW_ASPECT aspect);
extern QString GET_ASPECT_NAME(VIEW_ASPECT aspect);
extern QString GET_ASPECT_ICON(VIEW_ASPECT aspect);
extern VIEW_ASPECT GET_ASPECT_FROM_KIND(QString aspectKind);
extern QStringList GET_ASPECT_NAMES();

/*
extern QColor GET_INVERT_COLOR(VIEW_THEME theme);
extern QColor GET_TEXT_COLOR(VIEW_THEME theme, bool invert = false);
extern QColor GET_ASPECT_COLOR(VIEW_ASPECT aspect);
extern QColor GET_VIEW_COLOR(VIEW_THEME theme, COLOR_SHADE shade = NORMAL_SHADE);
extern QString GET_VIEW_COLOR_STRING(VIEW_THEME theme, COLOR_SHADE shade = NORMAL_SHADE);
extern QString GET_COLOR_STRING(QColor color, COLOR_SHADE shade = NORMAL_SHADE);
extern QString GET_DOCK_LABEL(DOCK_TYPE type);

extern QColor GET_HARDWARE_HIGHLIGHT_COLOR();
*/

#endif // ENUMERATIONC_H
