

typedef sequence<string, 10> str_10;
typedef sequence<string> str_u;


/// Put the interfaces in a module, to avoid global namespace pollution
struct Basic3{
    string str_val;
    str_10 strings;
};


/// A very simple interface
interface SequenceTest
{
	Basic3 send(in Basic3 message);
};